require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "app/helpers/*.rb"
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "config/environments/*.rb"
    - "bin/*"

Style/Documentation:
  Exclude:
    - "app/models/*"
    - "app/controllers/*"

Lint/MissingSuper:
  Exclude:
    - "app/components/*_component.rb"
