require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "app/helpers/*.rb"
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "config/environments/*.rb"
    - "bin/*"

Style/Documentation:
  Enabled: false