databases:
  - name: scails
    databaseName: scails
    user: scails

services:
  - type: web
    name: scails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
